# Generated by Django 6.1.1 on 2026-09-10 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other'), ('N', 'Prefer not to say')], max_length=1)),
                ('full_name', models.CharField(blank=True, max_length=100)),
                ('twitter_handle', models.URLField(blank=True, null=True)),
                ('whatsapp_handle', models.URLField(blank=True, null=True)),
                ('facebook_handle', models.URLField(blank=True, null=True)),
                ('speciality', models.JSONField(blank=True, default=list, null=True)),
                ('bio', models.TextField()),
                ('role', models.CharField(choices=[('FOUNDER', 'Founder'), ('CO-FOUNDER', 'Co-Founder'), ('JOURNALIST', 'Journalist')], max_length=10)),
                ('tribute_bio', models.TextField(blank=True, null=True)),
                ('last_promotion', models.DateField(blank=True, null=True)),
                ('auth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
