# Generated by Django 6.1.1 on 2026-09-10 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='get_blog_notification',
            field=models.BooleanField(default=True),
        ),
    ]
