# Generated by Django 6.1.1 on 2026-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0003_staffprofile_followrelationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffprofile',
            options={'verbose_name': 'Staff profile', 'verbose_name_plural': 'Staff profiles'},
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('FOUNDER', 'Founder'), ('CO-FOUNDER', 'Co-Founder'), ('JOURNALIST', 'Journalist')], default='JOURNALIST', max_length=10),
        ),
    ]
