# Generated by Django 6.1.1 on 2026-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0004_alter_staffprofile_options_alter_staffprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='role',
            field=models.CharField(blank=True, choices=[('FOUNDER', 'Founder'), ('CO-FOUNDER', 'Co-Founder'), ('SNR-JOURNALIST', 'Snr-Journalist'), ('JOURNALIST', 'Journalist')], default='JOURNALIST', max_length=20),
        ),
    ]
