# Generated by Django 6.1.1 on 2026-09-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('STAFF', '0005_alter_staffprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1),
        ),
    ]
