# Generated by Django 6.1.1 on 2026-09-10 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.URLField(blank=True, null=True)),
                ('image_info', models.CharField(default='The image is self explanatory.', max_length=20)),
                ('category', models.CharField(choices=[('UNIVERSITY', 'UNIVERSITY'), ('POLYTECHNIC', 'POLYTECHNIC'), ('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('POSTUTME', 'POSTUTME'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('GENERAL', 'GENERAL')], max_length=20)),
                ('heading', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('views', models.PositiveIntegerField(db_index=True, default=0)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to=settings.AUTH_USER_MODEL)),
                ('non_anonymous_viewer', models.ManyToManyField(blank=True, related_name='non_anonymous_viewer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='BLOG.blog')),
            ],
        ),
    ]
