# Generated by Django 6.1.1 on 2026-09-10 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image_info',
            field=models.CharField(default='The image is self explanatory.', max_length=100),
        ),
    ]
