# Generated by Django 6.1.1 on 2026-09-11 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0002_alter_blog_image_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
