# Generated by Django 6.1.1 on 2026-09-11 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0003_blog_likes_comment_likes'),
    ]

    operations = []
