# Generated by Django 6.1.1 on 2026-09-17 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BLOG', '0006_blog_unique_story_heading_author_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('UNIVERSITY', 'UNIVERSITY'), ('POLYTECHNIC', 'POLYTECHNIC'), ('JAMB', 'JAMB'), ('WAEC', 'WAEC'), ('POSTUTME', 'POSTUTME'), ('SCHOLARSHIP', 'SCHOLARSHIP'), ('TECHNOLOGY', 'TECHNOLOGY'), ('GENERAL', 'GENERAL')], max_length=20),
        ),
    ]
